# Generated by Django 4.2.4 on 2023-08-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="номер чата"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="update_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="номер последнего сообщения",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="никнейм в телеграм"
            ),
        ),
    ]
