# Generated by Django 4.2.4 on 2023-08-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_chat_id_user_update_id_alter_user_telegram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="chat_id",
            field=models.PositiveBigIntegerField(
                blank=True, default=0, null=True, verbose_name="номер чата"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="update_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="номер последнего сообщения",
            ),
        ),
    ]
