# Generated by Django 4.2.4 on 2023-08-09 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=150, verbose_name="место")),
                ("time", models.TimeField(verbose_name="время")),
                ("action", models.CharField(max_length=150, verbose_name="действие")),
                ("nice", models.BooleanField(default=False, verbose_name="приятная")),
                ("period", models.SmallIntegerField(verbose_name="периодичность")),
                (
                    "reward",
                    models.CharField(max_length=150, verbose_name="вознаграждение"),
                ),
                ("length", models.SmallIntegerField(verbose_name="продолжительность")),
                (
                    "public",
                    models.BooleanField(default=False, verbose_name="публичная"),
                ),
                (
                    "linked",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
