# Generated by Django 4.2.4 on 2023-08-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="периодичность"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="место"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="вознаграждение"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="время"),
        ),
    ]
